/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedBankRouteImport } from './routes/_authenticated/bank'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedSkapaRouteImport } from './routes/_authenticated/skapa'
import { Route as AuthenticatedTeamsRouteImport } from './routes/_authenticated/teams'
import { Route as TShareIdRouteImport } from './routes/t.$shareId'
import { Route as AuthenticatedTacticIdRouteImport } from './routes/_authenticated/tactic.$id'
import { Route as AuthenticatedTaktikbankIndexRouteImport } from './routes/_authenticated/taktikbank.index'
import { Route as AuthenticatedTaktikbankCardIdRouteImport } from './routes/_authenticated/taktikbank.$cardId'
import { Route as AuthenticatedTeamTeamIdRouteImport } from './routes/_authenticated/team.$teamId'
import { Route as AuthenticatedTeamTeamIdIndexRouteImport } from './routes/_authenticated/team.$teamId.index'
import { Route as AuthenticatedTeamTeamIdAboutRouteImport } from './routes/_authenticated/team.$teamId.about'
import { Route as AuthenticatedTeamTeamIdCalendarRouteImport } from './routes/_authenticated/team.$teamId.calendar'
import { Route as AuthenticatedTeamTeamIdMatchesRouteImport } from './routes/_authenticated/team.$teamId.matches'
import { Route as AuthenticatedTeamTeamIdPhotosRouteImport } from './routes/_authenticated/team.$teamId.photos'
import { Route as AuthenticatedTeamTeamIdTrainingRouteImport } from './routes/_authenticated/team.$teamId.training'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBankRoute = AuthenticatedBankRouteImport.update({
  id: '/bank',
  path: '/bank',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSkapaRoute = AuthenticatedSkapaRouteImport.update({
  id: '/skapa',
  path: '/skapa',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTeamsRoute = AuthenticatedTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const TShareIdRoute = TShareIdRouteImport.update({
  id: '/t/$shareId',
  path: '/t/$shareId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTacticIdRoute = AuthenticatedTacticIdRouteImport.update({
  id: '/tactic/$id',
  path: '/tactic/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTaktikbankIndexRoute =
  AuthenticatedTaktikbankIndexRouteImport.update({
    id: '/taktikbank/',
    path: '/taktikbank/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTaktikbankCardIdRoute =
  AuthenticatedTaktikbankCardIdRouteImport.update({
    id: '/taktikbank/$cardId',
    path: '/taktikbank/$cardId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTeamTeamIdRoute = AuthenticatedTeamTeamIdRouteImport.update({
  id: '/team/$teamId',
  path: '/team/$teamId',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTeamTeamIdIndexRoute =
  AuthenticatedTeamTeamIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedTeamTeamIdRoute,
  } as any)
const AuthenticatedTeamTeamIdAboutRoute =
  AuthenticatedTeamTeamIdAboutRouteImport.update({
    id: '/about',
    path: '/about',
    getParentRoute: () => AuthenticatedTeamTeamIdRoute,
  } as any)
const AuthenticatedTeamTeamIdCalendarRoute =
  AuthenticatedTeamTeamIdCalendarRouteImport.update({
    id: '/calendar',
    path: '/calendar',
    getParentRoute: () => AuthenticatedTeamTeamIdRoute,
  } as any)
const AuthenticatedTeamTeamIdMatchesRoute =
  AuthenticatedTeamTeamIdMatchesRouteImport.update({
    id: '/matches',
    path: '/matches',
    getParentRoute: () => AuthenticatedTeamTeamIdRoute,
  } as any)
const AuthenticatedTeamTeamIdPhotosRoute =
  AuthenticatedTeamTeamIdPhotosRouteImport.update({
    id: '/photos',
    path: '/photos',
    getParentRoute: () => AuthenticatedTeamTeamIdRoute,
  } as any)
const AuthenticatedTeamTeamIdTrainingRoute =
  AuthenticatedTeamTeamIdTrainingRouteImport.update({
    id: '/training',
    path: '/training',
    getParentRoute: () => AuthenticatedTeamTeamIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/bank': typeof AuthenticatedBankRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/skapa': typeof AuthenticatedSkapaRoute
  '/teams': typeof AuthenticatedTeamsRoute
  '/t/$shareId': typeof TShareIdRoute
  '/tactic/$id': typeof AuthenticatedTacticIdRoute
  '/taktikbank/$cardId': typeof AuthenticatedTaktikbankCardIdRoute
  '/team/$teamId': typeof AuthenticatedTeamTeamIdRouteWithChildren
  '/taktikbank/': typeof AuthenticatedTaktikbankIndexRoute
  '/team/$teamId/about': typeof AuthenticatedTeamTeamIdAboutRoute
  '/team/$teamId/calendar': typeof AuthenticatedTeamTeamIdCalendarRoute
  '/team/$teamId/matches': typeof AuthenticatedTeamTeamIdMatchesRoute
  '/team/$teamId/photos': typeof AuthenticatedTeamTeamIdPhotosRoute
  '/team/$teamId/training': typeof AuthenticatedTeamTeamIdTrainingRoute
  '/team/$teamId/': typeof AuthenticatedTeamTeamIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/bank': typeof AuthenticatedBankRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/skapa': typeof AuthenticatedSkapaRoute
  '/teams': typeof AuthenticatedTeamsRoute
  '/t/$shareId': typeof TShareIdRoute
  '/tactic/$id': typeof AuthenticatedTacticIdRoute
  '/taktikbank/$cardId': typeof AuthenticatedTaktikbankCardIdRoute
  '/taktikbank': typeof AuthenticatedTaktikbankIndexRoute
  '/team/$teamId/about': typeof AuthenticatedTeamTeamIdAboutRoute
  '/team/$teamId/calendar': typeof AuthenticatedTeamTeamIdCalendarRoute
  '/team/$teamId/matches': typeof AuthenticatedTeamTeamIdMatchesRoute
  '/team/$teamId/photos': typeof AuthenticatedTeamTeamIdPhotosRoute
  '/team/$teamId/training': typeof AuthenticatedTeamTeamIdTrainingRoute
  '/team/$teamId': typeof AuthenticatedTeamTeamIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/bank': typeof AuthenticatedBankRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/skapa': typeof AuthenticatedSkapaRoute
  '/_authenticated/teams': typeof AuthenticatedTeamsRoute
  '/t/$shareId': typeof TShareIdRoute
  '/_authenticated/tactic/$id': typeof AuthenticatedTacticIdRoute
  '/_authenticated/taktikbank/$cardId': typeof AuthenticatedTaktikbankCardIdRoute
  '/_authenticated/team/$teamId': typeof AuthenticatedTeamTeamIdRouteWithChildren
  '/_authenticated/taktikbank/': typeof AuthenticatedTaktikbankIndexRoute
  '/_authenticated/team/$teamId/about': typeof AuthenticatedTeamTeamIdAboutRoute
  '/_authenticated/team/$teamId/calendar': typeof AuthenticatedTeamTeamIdCalendarRoute
  '/_authenticated/team/$teamId/matches': typeof AuthenticatedTeamTeamIdMatchesRoute
  '/_authenticated/team/$teamId/photos': typeof AuthenticatedTeamTeamIdPhotosRoute
  '/_authenticated/team/$teamId/training': typeof AuthenticatedTeamTeamIdTrainingRoute
  '/_authenticated/team/$teamId/': typeof AuthenticatedTeamTeamIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/bank'
    | '/onboarding'
    | '/skapa'
    | '/teams'
    | '/t/$shareId'
    | '/tactic/$id'
    | '/taktikbank/$cardId'
    | '/team/$teamId'
    | '/taktikbank/'
    | '/team/$teamId/about'
    | '/team/$teamId/calendar'
    | '/team/$teamId/matches'
    | '/team/$teamId/photos'
    | '/team/$teamId/training'
    | '/team/$teamId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/bank'
    | '/onboarding'
    | '/skapa'
    | '/teams'
    | '/t/$shareId'
    | '/tactic/$id'
    | '/taktikbank/$cardId'
    | '/taktikbank'
    | '/team/$teamId/about'
    | '/team/$teamId/calendar'
    | '/team/$teamId/matches'
    | '/team/$teamId/photos'
    | '/team/$teamId/training'
    | '/team/$teamId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/bank'
    | '/_authenticated/onboarding'
    | '/_authenticated/skapa'
    | '/_authenticated/teams'
    | '/t/$shareId'
    | '/_authenticated/tactic/$id'
    | '/_authenticated/taktikbank/$cardId'
    | '/_authenticated/team/$teamId'
    | '/_authenticated/taktikbank/'
    | '/_authenticated/team/$teamId/about'
    | '/_authenticated/team/$teamId/calendar'
    | '/_authenticated/team/$teamId/matches'
    | '/_authenticated/team/$teamId/photos'
    | '/_authenticated/team/$teamId/training'
    | '/_authenticated/team/$teamId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  TShareIdRoute: typeof TShareIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bank': {
      id: '/_authenticated/bank'
      path: '/bank'
      fullPath: '/bank'
      preLoaderRoute: typeof AuthenticatedBankRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/skapa': {
      id: '/_authenticated/skapa'
      path: '/skapa'
      fullPath: '/skapa'
      preLoaderRoute: typeof AuthenticatedSkapaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/teams': {
      id: '/_authenticated/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof AuthenticatedTeamsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/t/$shareId': {
      id: '/t/$shareId'
      path: '/t/$shareId'
      fullPath: '/t/$shareId'
      preLoaderRoute: typeof TShareIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tactic/$id': {
      id: '/_authenticated/tactic/$id'
      path: '/tactic/$id'
      fullPath: '/tactic/$id'
      preLoaderRoute: typeof AuthenticatedTacticIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/taktikbank/': {
      id: '/_authenticated/taktikbank/'
      path: '/taktikbank'
      fullPath: '/taktikbank/'
      preLoaderRoute: typeof AuthenticatedTaktikbankIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/taktikbank/$cardId': {
      id: '/_authenticated/taktikbank/$cardId'
      path: '/taktikbank/$cardId'
      fullPath: '/taktikbank/$cardId'
      preLoaderRoute: typeof AuthenticatedTaktikbankCardIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/team/$teamId': {
      id: '/_authenticated/team/$teamId'
      path: '/team/$teamId'
      fullPath: '/team/$teamId'
      preLoaderRoute: typeof AuthenticatedTeamTeamIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/team/$teamId/': {
      id: '/_authenticated/team/$teamId/'
      path: '/'
      fullPath: '/team/$teamId/'
      preLoaderRoute: typeof AuthenticatedTeamTeamIdIndexRouteImport
      parentRoute: typeof AuthenticatedTeamTeamIdRoute
    }
    '/_authenticated/team/$teamId/about': {
      id: '/_authenticated/team/$teamId/about'
      path: '/about'
      fullPath: '/team/$teamId/about'
      preLoaderRoute: typeof AuthenticatedTeamTeamIdAboutRouteImport
      parentRoute: typeof AuthenticatedTeamTeamIdRoute
    }
    '/_authenticated/team/$teamId/calendar': {
      id: '/_authenticated/team/$teamId/calendar'
      path: '/calendar'
      fullPath: '/team/$teamId/calendar'
      preLoaderRoute: typeof AuthenticatedTeamTeamIdCalendarRouteImport
      parentRoute: typeof AuthenticatedTeamTeamIdRoute
    }
    '/_authenticated/team/$teamId/matches': {
      id: '/_authenticated/team/$teamId/matches'
      path: '/matches'
      fullPath: '/team/$teamId/matches'
      preLoaderRoute: typeof AuthenticatedTeamTeamIdMatchesRouteImport
      parentRoute: typeof AuthenticatedTeamTeamIdRoute
    }
    '/_authenticated/team/$teamId/photos': {
      id: '/_authenticated/team/$teamId/photos'
      path: '/photos'
      fullPath: '/team/$teamId/photos'
      preLoaderRoute: typeof AuthenticatedTeamTeamIdPhotosRouteImport
      parentRoute: typeof AuthenticatedTeamTeamIdRoute
    }
    '/_authenticated/team/$teamId/training': {
      id: '/_authenticated/team/$teamId/training'
      path: '/training'
      fullPath: '/team/$teamId/training'
      preLoaderRoute: typeof AuthenticatedTeamTeamIdTrainingRouteImport
      parentRoute: typeof AuthenticatedTeamTeamIdRoute
    }
  }
}

interface AuthenticatedTeamTeamIdRouteChildren {
  AuthenticatedTeamTeamIdAboutRoute: typeof AuthenticatedTeamTeamIdAboutRoute
  AuthenticatedTeamTeamIdCalendarRoute: typeof AuthenticatedTeamTeamIdCalendarRoute
  AuthenticatedTeamTeamIdMatchesRoute: typeof AuthenticatedTeamTeamIdMatchesRoute
  AuthenticatedTeamTeamIdPhotosRoute: typeof AuthenticatedTeamTeamIdPhotosRoute
  AuthenticatedTeamTeamIdTrainingRoute: typeof AuthenticatedTeamTeamIdTrainingRoute
  AuthenticatedTeamTeamIdIndexRoute: typeof AuthenticatedTeamTeamIdIndexRoute
}

const AuthenticatedTeamTeamIdRouteChildren: AuthenticatedTeamTeamIdRouteChildren =
  {
    AuthenticatedTeamTeamIdAboutRoute: AuthenticatedTeamTeamIdAboutRoute,
    AuthenticatedTeamTeamIdCalendarRoute: AuthenticatedTeamTeamIdCalendarRoute,
    AuthenticatedTeamTeamIdMatchesRoute: AuthenticatedTeamTeamIdMatchesRoute,
    AuthenticatedTeamTeamIdPhotosRoute: AuthenticatedTeamTeamIdPhotosRoute,
    AuthenticatedTeamTeamIdTrainingRoute: AuthenticatedTeamTeamIdTrainingRoute,
    AuthenticatedTeamTeamIdIndexRoute: AuthenticatedTeamTeamIdIndexRoute,
  }

const AuthenticatedTeamTeamIdRouteWithChildren =
  AuthenticatedTeamTeamIdRoute._addFileChildren(
    AuthenticatedTeamTeamIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedBankRoute: typeof AuthenticatedBankRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedSkapaRoute: typeof AuthenticatedSkapaRoute
  AuthenticatedTeamsRoute: typeof AuthenticatedTeamsRoute
  AuthenticatedTacticIdRoute: typeof AuthenticatedTacticIdRoute
  AuthenticatedTaktikbankCardIdRoute: typeof AuthenticatedTaktikbankCardIdRoute
  AuthenticatedTeamTeamIdRoute: typeof AuthenticatedTeamTeamIdRouteWithChildren
  AuthenticatedTaktikbankIndexRoute: typeof AuthenticatedTaktikbankIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedBankRoute: AuthenticatedBankRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedSkapaRoute: AuthenticatedSkapaRoute,
  AuthenticatedTeamsRoute: AuthenticatedTeamsRoute,
  AuthenticatedTacticIdRoute: AuthenticatedTacticIdRoute,
  AuthenticatedTaktikbankCardIdRoute: AuthenticatedTaktikbankCardIdRoute,
  AuthenticatedTeamTeamIdRoute: AuthenticatedTeamTeamIdRouteWithChildren,
  AuthenticatedTaktikbankIndexRoute: AuthenticatedTaktikbankIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  TShareIdRoute: TShareIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
