/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedBankRouteImport } from './routes/_authenticated/bank'
import { Route as AuthenticatedInstallningarRouteImport } from './routes/_authenticated/installningar'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedSkapaRouteImport } from './routes/_authenticated/skapa'
import { Route as AuthenticatedTeamsRouteImport } from './routes/_authenticated/teams'
import { Route as TShareIdRouteImport } from './routes/t.$shareId'
import { Route as AuthenticatedKunskapsbankIndexRouteImport } from './routes/_authenticated/kunskapsbank.index'
import { Route as AuthenticatedKunskapsbankSlugRouteImport } from './routes/_authenticated/kunskapsbank.$slug'
import { Route as AuthenticatedOvningsbankIndexRouteImport } from './routes/_authenticated/ovningsbank.index'
import { Route as AuthenticatedTacticIdRouteImport } from './routes/_authenticated/tactic.$id'
import { Route as AuthenticatedTaktikbankIndexRouteImport } from './routes/_authenticated/taktikbank.index'
import { Route as AuthenticatedTaktikbankCardIdRouteImport } from './routes/_authenticated/taktikbank.$cardId'
import { Route as AuthenticatedTaktikbankReglerRouteImport } from './routes/_authenticated/taktikbank.regler'
import { Route as AuthenticatedTeamTeamIdRouteImport } from './routes/_authenticated/team.$teamId'
import { Route as AuthenticatedTraningspassIndexRouteImport } from './routes/_authenticated/traningspass.index'
import { Route as AuthenticatedTraningspassIdRouteImport } from './routes/_authenticated/traningspass.$id'
import { Route as AuthenticatedTeamTeamIdIndexRouteImport } from './routes/_authenticated/team.$teamId.index'
import { Route as AuthenticatedTeamTeamIdAboutRouteImport } from './routes/_authenticated/team.$teamId.about'
import { Route as AuthenticatedTeamTeamIdCalendarRouteImport } from './routes/_authenticated/team.$teamId.calendar'
import { Route as AuthenticatedTeamTeamIdLeadersRouteImport } from './routes/_authenticated/team.$teamId.leaders'
import { Route as AuthenticatedTeamTeamIdMatchesRouteImport } from './routes/_authenticated/team.$teamId.matches'
import { Route as AuthenticatedTeamTeamIdNarvaroRouteImport } from './routes/_authenticated/team.$teamId.narvaro'
import { Route as AuthenticatedTeamTeamIdPhotosRouteImport } from './routes/_authenticated/team.$teamId.photos'
import { Route as AuthenticatedTeamTeamIdStatistikRouteImport } from './routes/_authenticated/team.$teamId.statistik'
import { Route as AuthenticatedTeamTeamIdTrainingRouteImport } from './routes/_authenticated/team.$teamId.training'
import { Route as AuthenticatedTraningspassIdIndexRouteImport } from './routes/_authenticated/traningspass.$id.index'
import { Route as AuthenticatedTraningspassIdVisaRouteImport } from './routes/_authenticated/traningspass.$id.visa'
import { Route as AuthenticatedTeamTeamIdPlayerPlayerIdRouteImport } from './routes/_authenticated/team.$teamId.player.$playerId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBankRoute = AuthenticatedBankRouteImport.update({
  id: '/bank',
  path: '/bank',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInstallningarRoute =
  AuthenticatedInstallningarRouteImport.update({
    id: '/installningar',
    path: '/installningar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSkapaRoute = AuthenticatedSkapaRouteImport.update({
  id: '/skapa',
  path: '/skapa',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTeamsRoute = AuthenticatedTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const TShareIdRoute = TShareIdRouteImport.update({
  id: '/t/$shareId',
  path: '/t/$shareId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedKunskapsbankIndexRoute =
  AuthenticatedKunskapsbankIndexRouteImport.update({
    id: '/kunskapsbank/',
    path: '/kunskapsbank/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedKunskapsbankSlugRoute =
  AuthenticatedKunskapsbankSlugRouteImport.update({
    id: '/kunskapsbank/$slug',
    path: '/kunskapsbank/$slug',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOvningsbankIndexRoute =
  AuthenticatedOvningsbankIndexRouteImport.update({
    id: '/ovningsbank/',
    path: '/ovningsbank/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTacticIdRoute = AuthenticatedTacticIdRouteImport.update({
  id: '/tactic/$id',
  path: '/tactic/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTaktikbankIndexRoute =
  AuthenticatedTaktikbankIndexRouteImport.update({
    id: '/taktikbank/',
    path: '/taktikbank/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTaktikbankCardIdRoute =
  AuthenticatedTaktikbankCardIdRouteImport.update({
    id: '/taktikbank/$cardId',
    path: '/taktikbank/$cardId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTaktikbankReglerRoute =
  AuthenticatedTaktikbankReglerRouteImport.update({
    id: '/taktikbank/regler',
    path: '/taktikbank/regler',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTeamTeamIdRoute = AuthenticatedTeamTeamIdRouteImport.update({
  id: '/team/$teamId',
  path: '/team/$teamId',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTraningspassIndexRoute =
  AuthenticatedTraningspassIndexRouteImport.update({
    id: '/traningspass/',
    path: '/traningspass/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTraningspassIdRoute =
  AuthenticatedTraningspassIdRouteImport.update({
    id: '/traningspass/$id',
    path: '/traningspass/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTeamTeamIdIndexRoute =
  AuthenticatedTeamTeamIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedTeamTeamIdRoute,
  } as any)
const AuthenticatedTeamTeamIdAboutRoute =
  AuthenticatedTeamTeamIdAboutRouteImport.update({
    id: '/about',
    path: '/about',
    getParentRoute: () => AuthenticatedTeamTeamIdRoute,
  } as any)
const AuthenticatedTeamTeamIdCalendarRoute =
  AuthenticatedTeamTeamIdCalendarRouteImport.update({
    id: '/calendar',
    path: '/calendar',
    getParentRoute: () => AuthenticatedTeamTeamIdRoute,
  } as any)
const AuthenticatedTeamTeamIdLeadersRoute =
  AuthenticatedTeamTeamIdLeadersRouteImport.update({
    id: '/leaders',
    path: '/leaders',
    getParentRoute: () => AuthenticatedTeamTeamIdRoute,
  } as any)
const AuthenticatedTeamTeamIdMatchesRoute =
  AuthenticatedTeamTeamIdMatchesRouteImport.update({
    id: '/matches',
    path: '/matches',
    getParentRoute: () => AuthenticatedTeamTeamIdRoute,
  } as any)
const AuthenticatedTeamTeamIdNarvaroRoute =
  AuthenticatedTeamTeamIdNarvaroRouteImport.update({
    id: '/narvaro',
    path: '/narvaro',
    getParentRoute: () => AuthenticatedTeamTeamIdRoute,
  } as any)
const AuthenticatedTeamTeamIdPhotosRoute =
  AuthenticatedTeamTeamIdPhotosRouteImport.update({
    id: '/photos',
    path: '/photos',
    getParentRoute: () => AuthenticatedTeamTeamIdRoute,
  } as any)
const AuthenticatedTeamTeamIdStatistikRoute =
  AuthenticatedTeamTeamIdStatistikRouteImport.update({
    id: '/statistik',
    path: '/statistik',
    getParentRoute: () => AuthenticatedTeamTeamIdRoute,
  } as any)
const AuthenticatedTeamTeamIdTrainingRoute =
  AuthenticatedTeamTeamIdTrainingRouteImport.update({
    id: '/training',
    path: '/training',
    getParentRoute: () => AuthenticatedTeamTeamIdRoute,
  } as any)
const AuthenticatedTraningspassIdIndexRoute =
  AuthenticatedTraningspassIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedTraningspassIdRoute,
  } as any)
const AuthenticatedTraningspassIdVisaRoute =
  AuthenticatedTraningspassIdVisaRouteImport.update({
    id: '/visa',
    path: '/visa',
    getParentRoute: () => AuthenticatedTraningspassIdRoute,
  } as any)
const AuthenticatedTeamTeamIdPlayerPlayerIdRoute =
  AuthenticatedTeamTeamIdPlayerPlayerIdRouteImport.update({
    id: '/player/$playerId',
    path: '/player/$playerId',
    getParentRoute: () => AuthenticatedTeamTeamIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/bank': typeof AuthenticatedBankRoute
  '/installningar': typeof AuthenticatedInstallningarRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/skapa': typeof AuthenticatedSkapaRoute
  '/teams': typeof AuthenticatedTeamsRoute
  '/t/$shareId': typeof TShareIdRoute
  '/kunskapsbank/$slug': typeof AuthenticatedKunskapsbankSlugRoute
  '/tactic/$id': typeof AuthenticatedTacticIdRoute
  '/taktikbank/$cardId': typeof AuthenticatedTaktikbankCardIdRoute
  '/taktikbank/regler': typeof AuthenticatedTaktikbankReglerRoute
  '/team/$teamId': typeof AuthenticatedTeamTeamIdRouteWithChildren
  '/traningspass/$id': typeof AuthenticatedTraningspassIdRouteWithChildren
  '/kunskapsbank/': typeof AuthenticatedKunskapsbankIndexRoute
  '/ovningsbank/': typeof AuthenticatedOvningsbankIndexRoute
  '/taktikbank/': typeof AuthenticatedTaktikbankIndexRoute
  '/traningspass/': typeof AuthenticatedTraningspassIndexRoute
  '/team/$teamId/about': typeof AuthenticatedTeamTeamIdAboutRoute
  '/team/$teamId/calendar': typeof AuthenticatedTeamTeamIdCalendarRoute
  '/team/$teamId/leaders': typeof AuthenticatedTeamTeamIdLeadersRoute
  '/team/$teamId/matches': typeof AuthenticatedTeamTeamIdMatchesRoute
  '/team/$teamId/narvaro': typeof AuthenticatedTeamTeamIdNarvaroRoute
  '/team/$teamId/photos': typeof AuthenticatedTeamTeamIdPhotosRoute
  '/team/$teamId/statistik': typeof AuthenticatedTeamTeamIdStatistikRoute
  '/team/$teamId/training': typeof AuthenticatedTeamTeamIdTrainingRoute
  '/traningspass/$id/visa': typeof AuthenticatedTraningspassIdVisaRoute
  '/team/$teamId/': typeof AuthenticatedTeamTeamIdIndexRoute
  '/traningspass/$id/': typeof AuthenticatedTraningspassIdIndexRoute
  '/team/$teamId/player/$playerId': typeof AuthenticatedTeamTeamIdPlayerPlayerIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/bank': typeof AuthenticatedBankRoute
  '/installningar': typeof AuthenticatedInstallningarRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/skapa': typeof AuthenticatedSkapaRoute
  '/teams': typeof AuthenticatedTeamsRoute
  '/t/$shareId': typeof TShareIdRoute
  '/kunskapsbank/$slug': typeof AuthenticatedKunskapsbankSlugRoute
  '/tactic/$id': typeof AuthenticatedTacticIdRoute
  '/taktikbank/$cardId': typeof AuthenticatedTaktikbankCardIdRoute
  '/taktikbank/regler': typeof AuthenticatedTaktikbankReglerRoute
  '/kunskapsbank': typeof AuthenticatedKunskapsbankIndexRoute
  '/ovningsbank': typeof AuthenticatedOvningsbankIndexRoute
  '/taktikbank': typeof AuthenticatedTaktikbankIndexRoute
  '/traningspass': typeof AuthenticatedTraningspassIndexRoute
  '/team/$teamId/about': typeof AuthenticatedTeamTeamIdAboutRoute
  '/team/$teamId/calendar': typeof AuthenticatedTeamTeamIdCalendarRoute
  '/team/$teamId/leaders': typeof AuthenticatedTeamTeamIdLeadersRoute
  '/team/$teamId/matches': typeof AuthenticatedTeamTeamIdMatchesRoute
  '/team/$teamId/narvaro': typeof AuthenticatedTeamTeamIdNarvaroRoute
  '/team/$teamId/photos': typeof AuthenticatedTeamTeamIdPhotosRoute
  '/team/$teamId/statistik': typeof AuthenticatedTeamTeamIdStatistikRoute
  '/team/$teamId/training': typeof AuthenticatedTeamTeamIdTrainingRoute
  '/traningspass/$id/visa': typeof AuthenticatedTraningspassIdVisaRoute
  '/team/$teamId': typeof AuthenticatedTeamTeamIdIndexRoute
  '/traningspass/$id': typeof AuthenticatedTraningspassIdIndexRoute
  '/team/$teamId/player/$playerId': typeof AuthenticatedTeamTeamIdPlayerPlayerIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/bank': typeof AuthenticatedBankRoute
  '/_authenticated/installningar': typeof AuthenticatedInstallningarRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/skapa': typeof AuthenticatedSkapaRoute
  '/_authenticated/teams': typeof AuthenticatedTeamsRoute
  '/t/$shareId': typeof TShareIdRoute
  '/_authenticated/kunskapsbank/$slug': typeof AuthenticatedKunskapsbankSlugRoute
  '/_authenticated/tactic/$id': typeof AuthenticatedTacticIdRoute
  '/_authenticated/taktikbank/$cardId': typeof AuthenticatedTaktikbankCardIdRoute
  '/_authenticated/taktikbank/regler': typeof AuthenticatedTaktikbankReglerRoute
  '/_authenticated/team/$teamId': typeof AuthenticatedTeamTeamIdRouteWithChildren
  '/_authenticated/traningspass/$id': typeof AuthenticatedTraningspassIdRouteWithChildren
  '/_authenticated/kunskapsbank/': typeof AuthenticatedKunskapsbankIndexRoute
  '/_authenticated/ovningsbank/': typeof AuthenticatedOvningsbankIndexRoute
  '/_authenticated/taktikbank/': typeof AuthenticatedTaktikbankIndexRoute
  '/_authenticated/traningspass/': typeof AuthenticatedTraningspassIndexRoute
  '/_authenticated/team/$teamId/about': typeof AuthenticatedTeamTeamIdAboutRoute
  '/_authenticated/team/$teamId/calendar': typeof AuthenticatedTeamTeamIdCalendarRoute
  '/_authenticated/team/$teamId/leaders': typeof AuthenticatedTeamTeamIdLeadersRoute
  '/_authenticated/team/$teamId/matches': typeof AuthenticatedTeamTeamIdMatchesRoute
  '/_authenticated/team/$teamId/narvaro': typeof AuthenticatedTeamTeamIdNarvaroRoute
  '/_authenticated/team/$teamId/photos': typeof AuthenticatedTeamTeamIdPhotosRoute
  '/_authenticated/team/$teamId/statistik': typeof AuthenticatedTeamTeamIdStatistikRoute
  '/_authenticated/team/$teamId/training': typeof AuthenticatedTeamTeamIdTrainingRoute
  '/_authenticated/traningspass/$id/visa': typeof AuthenticatedTraningspassIdVisaRoute
  '/_authenticated/team/$teamId/': typeof AuthenticatedTeamTeamIdIndexRoute
  '/_authenticated/traningspass/$id/': typeof AuthenticatedTraningspassIdIndexRoute
  '/_authenticated/team/$teamId/player/$playerId': typeof AuthenticatedTeamTeamIdPlayerPlayerIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/bank'
    | '/installningar'
    | '/onboarding'
    | '/skapa'
    | '/teams'
    | '/t/$shareId'
    | '/kunskapsbank/$slug'
    | '/tactic/$id'
    | '/taktikbank/$cardId'
    | '/taktikbank/regler'
    | '/team/$teamId'
    | '/traningspass/$id'
    | '/kunskapsbank/'
    | '/ovningsbank/'
    | '/taktikbank/'
    | '/traningspass/'
    | '/team/$teamId/about'
    | '/team/$teamId/calendar'
    | '/team/$teamId/leaders'
    | '/team/$teamId/matches'
    | '/team/$teamId/narvaro'
    | '/team/$teamId/photos'
    | '/team/$teamId/statistik'
    | '/team/$teamId/training'
    | '/traningspass/$id/visa'
    | '/team/$teamId/'
    | '/traningspass/$id/'
    | '/team/$teamId/player/$playerId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/bank'
    | '/installningar'
    | '/onboarding'
    | '/skapa'
    | '/teams'
    | '/t/$shareId'
    | '/kunskapsbank/$slug'
    | '/tactic/$id'
    | '/taktikbank/$cardId'
    | '/taktikbank/regler'
    | '/kunskapsbank'
    | '/ovningsbank'
    | '/taktikbank'
    | '/traningspass'
    | '/team/$teamId/about'
    | '/team/$teamId/calendar'
    | '/team/$teamId/leaders'
    | '/team/$teamId/matches'
    | '/team/$teamId/narvaro'
    | '/team/$teamId/photos'
    | '/team/$teamId/statistik'
    | '/team/$teamId/training'
    | '/traningspass/$id/visa'
    | '/team/$teamId'
    | '/traningspass/$id'
    | '/team/$teamId/player/$playerId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/bank'
    | '/_authenticated/installningar'
    | '/_authenticated/onboarding'
    | '/_authenticated/skapa'
    | '/_authenticated/teams'
    | '/t/$shareId'
    | '/_authenticated/kunskapsbank/$slug'
    | '/_authenticated/tactic/$id'
    | '/_authenticated/taktikbank/$cardId'
    | '/_authenticated/taktikbank/regler'
    | '/_authenticated/team/$teamId'
    | '/_authenticated/traningspass/$id'
    | '/_authenticated/kunskapsbank/'
    | '/_authenticated/ovningsbank/'
    | '/_authenticated/taktikbank/'
    | '/_authenticated/traningspass/'
    | '/_authenticated/team/$teamId/about'
    | '/_authenticated/team/$teamId/calendar'
    | '/_authenticated/team/$teamId/leaders'
    | '/_authenticated/team/$teamId/matches'
    | '/_authenticated/team/$teamId/narvaro'
    | '/_authenticated/team/$teamId/photos'
    | '/_authenticated/team/$teamId/statistik'
    | '/_authenticated/team/$teamId/training'
    | '/_authenticated/traningspass/$id/visa'
    | '/_authenticated/team/$teamId/'
    | '/_authenticated/traningspass/$id/'
    | '/_authenticated/team/$teamId/player/$playerId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  TShareIdRoute: typeof TShareIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bank': {
      id: '/_authenticated/bank'
      path: '/bank'
      fullPath: '/bank'
      preLoaderRoute: typeof AuthenticatedBankRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/installningar': {
      id: '/_authenticated/installningar'
      path: '/installningar'
      fullPath: '/installningar'
      preLoaderRoute: typeof AuthenticatedInstallningarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/skapa': {
      id: '/_authenticated/skapa'
      path: '/skapa'
      fullPath: '/skapa'
      preLoaderRoute: typeof AuthenticatedSkapaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/teams': {
      id: '/_authenticated/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof AuthenticatedTeamsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/t/$shareId': {
      id: '/t/$shareId'
      path: '/t/$shareId'
      fullPath: '/t/$shareId'
      preLoaderRoute: typeof TShareIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/kunskapsbank/': {
      id: '/_authenticated/kunskapsbank/'
      path: '/kunskapsbank'
      fullPath: '/kunskapsbank/'
      preLoaderRoute: typeof AuthenticatedKunskapsbankIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kunskapsbank/$slug': {
      id: '/_authenticated/kunskapsbank/$slug'
      path: '/kunskapsbank/$slug'
      fullPath: '/kunskapsbank/$slug'
      preLoaderRoute: typeof AuthenticatedKunskapsbankSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ovningsbank/': {
      id: '/_authenticated/ovningsbank/'
      path: '/ovningsbank'
      fullPath: '/ovningsbank/'
      preLoaderRoute: typeof AuthenticatedOvningsbankIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tactic/$id': {
      id: '/_authenticated/tactic/$id'
      path: '/tactic/$id'
      fullPath: '/tactic/$id'
      preLoaderRoute: typeof AuthenticatedTacticIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/taktikbank/': {
      id: '/_authenticated/taktikbank/'
      path: '/taktikbank'
      fullPath: '/taktikbank/'
      preLoaderRoute: typeof AuthenticatedTaktikbankIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/taktikbank/$cardId': {
      id: '/_authenticated/taktikbank/$cardId'
      path: '/taktikbank/$cardId'
      fullPath: '/taktikbank/$cardId'
      preLoaderRoute: typeof AuthenticatedTaktikbankCardIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/taktikbank/regler': {
      id: '/_authenticated/taktikbank/regler'
      path: '/taktikbank/regler'
      fullPath: '/taktikbank/regler'
      preLoaderRoute: typeof AuthenticatedTaktikbankReglerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/team/$teamId': {
      id: '/_authenticated/team/$teamId'
      path: '/team/$teamId'
      fullPath: '/team/$teamId'
      preLoaderRoute: typeof AuthenticatedTeamTeamIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/traningspass/': {
      id: '/_authenticated/traningspass/'
      path: '/traningspass'
      fullPath: '/traningspass/'
      preLoaderRoute: typeof AuthenticatedTraningspassIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/traningspass/$id': {
      id: '/_authenticated/traningspass/$id'
      path: '/traningspass/$id'
      fullPath: '/traningspass/$id'
      preLoaderRoute: typeof AuthenticatedTraningspassIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/team/$teamId/': {
      id: '/_authenticated/team/$teamId/'
      path: '/'
      fullPath: '/team/$teamId/'
      preLoaderRoute: typeof AuthenticatedTeamTeamIdIndexRouteImport
      parentRoute: typeof AuthenticatedTeamTeamIdRoute
    }
    '/_authenticated/team/$teamId/about': {
      id: '/_authenticated/team/$teamId/about'
      path: '/about'
      fullPath: '/team/$teamId/about'
      preLoaderRoute: typeof AuthenticatedTeamTeamIdAboutRouteImport
      parentRoute: typeof AuthenticatedTeamTeamIdRoute
    }
    '/_authenticated/team/$teamId/calendar': {
      id: '/_authenticated/team/$teamId/calendar'
      path: '/calendar'
      fullPath: '/team/$teamId/calendar'
      preLoaderRoute: typeof AuthenticatedTeamTeamIdCalendarRouteImport
      parentRoute: typeof AuthenticatedTeamTeamIdRoute
    }
    '/_authenticated/team/$teamId/leaders': {
      id: '/_authenticated/team/$teamId/leaders'
      path: '/leaders'
      fullPath: '/team/$teamId/leaders'
      preLoaderRoute: typeof AuthenticatedTeamTeamIdLeadersRouteImport
      parentRoute: typeof AuthenticatedTeamTeamIdRoute
    }
    '/_authenticated/team/$teamId/matches': {
      id: '/_authenticated/team/$teamId/matches'
      path: '/matches'
      fullPath: '/team/$teamId/matches'
      preLoaderRoute: typeof AuthenticatedTeamTeamIdMatchesRouteImport
      parentRoute: typeof AuthenticatedTeamTeamIdRoute
    }
    '/_authenticated/team/$teamId/narvaro': {
      id: '/_authenticated/team/$teamId/narvaro'
      path: '/narvaro'
      fullPath: '/team/$teamId/narvaro'
      preLoaderRoute: typeof AuthenticatedTeamTeamIdNarvaroRouteImport
      parentRoute: typeof AuthenticatedTeamTeamIdRoute
    }
    '/_authenticated/team/$teamId/photos': {
      id: '/_authenticated/team/$teamId/photos'
      path: '/photos'
      fullPath: '/team/$teamId/photos'
      preLoaderRoute: typeof AuthenticatedTeamTeamIdPhotosRouteImport
      parentRoute: typeof AuthenticatedTeamTeamIdRoute
    }
    '/_authenticated/team/$teamId/statistik': {
      id: '/_authenticated/team/$teamId/statistik'
      path: '/statistik'
      fullPath: '/team/$teamId/statistik'
      preLoaderRoute: typeof AuthenticatedTeamTeamIdStatistikRouteImport
      parentRoute: typeof AuthenticatedTeamTeamIdRoute
    }
    '/_authenticated/team/$teamId/training': {
      id: '/_authenticated/team/$teamId/training'
      path: '/training'
      fullPath: '/team/$teamId/training'
      preLoaderRoute: typeof AuthenticatedTeamTeamIdTrainingRouteImport
      parentRoute: typeof AuthenticatedTeamTeamIdRoute
    }
    '/_authenticated/traningspass/$id/': {
      id: '/_authenticated/traningspass/$id/'
      path: '/'
      fullPath: '/traningspass/$id/'
      preLoaderRoute: typeof AuthenticatedTraningspassIdIndexRouteImport
      parentRoute: typeof AuthenticatedTraningspassIdRoute
    }
    '/_authenticated/traningspass/$id/visa': {
      id: '/_authenticated/traningspass/$id/visa'
      path: '/visa'
      fullPath: '/traningspass/$id/visa'
      preLoaderRoute: typeof AuthenticatedTraningspassIdVisaRouteImport
      parentRoute: typeof AuthenticatedTraningspassIdRoute
    }
    '/_authenticated/team/$teamId/player/$playerId': {
      id: '/_authenticated/team/$teamId/player/$playerId'
      path: '/player/$playerId'
      fullPath: '/team/$teamId/player/$playerId'
      preLoaderRoute: typeof AuthenticatedTeamTeamIdPlayerPlayerIdRouteImport
      parentRoute: typeof AuthenticatedTeamTeamIdRoute
    }
  }
}

interface AuthenticatedTeamTeamIdRouteChildren {
  AuthenticatedTeamTeamIdAboutRoute: typeof AuthenticatedTeamTeamIdAboutRoute
  AuthenticatedTeamTeamIdCalendarRoute: typeof AuthenticatedTeamTeamIdCalendarRoute
  AuthenticatedTeamTeamIdLeadersRoute: typeof AuthenticatedTeamTeamIdLeadersRoute
  AuthenticatedTeamTeamIdMatchesRoute: typeof AuthenticatedTeamTeamIdMatchesRoute
  AuthenticatedTeamTeamIdNarvaroRoute: typeof AuthenticatedTeamTeamIdNarvaroRoute
  AuthenticatedTeamTeamIdPhotosRoute: typeof AuthenticatedTeamTeamIdPhotosRoute
  AuthenticatedTeamTeamIdStatistikRoute: typeof AuthenticatedTeamTeamIdStatistikRoute
  AuthenticatedTeamTeamIdTrainingRoute: typeof AuthenticatedTeamTeamIdTrainingRoute
  AuthenticatedTeamTeamIdIndexRoute: typeof AuthenticatedTeamTeamIdIndexRoute
  AuthenticatedTeamTeamIdPlayerPlayerIdRoute: typeof AuthenticatedTeamTeamIdPlayerPlayerIdRoute
}

const AuthenticatedTeamTeamIdRouteChildren: AuthenticatedTeamTeamIdRouteChildren =
  {
    AuthenticatedTeamTeamIdAboutRoute: AuthenticatedTeamTeamIdAboutRoute,
    AuthenticatedTeamTeamIdCalendarRoute: AuthenticatedTeamTeamIdCalendarRoute,
    AuthenticatedTeamTeamIdLeadersRoute: AuthenticatedTeamTeamIdLeadersRoute,
    AuthenticatedTeamTeamIdMatchesRoute: AuthenticatedTeamTeamIdMatchesRoute,
    AuthenticatedTeamTeamIdNarvaroRoute: AuthenticatedTeamTeamIdNarvaroRoute,
    AuthenticatedTeamTeamIdPhotosRoute: AuthenticatedTeamTeamIdPhotosRoute,
    AuthenticatedTeamTeamIdStatistikRoute:
      AuthenticatedTeamTeamIdStatistikRoute,
    AuthenticatedTeamTeamIdTrainingRoute: AuthenticatedTeamTeamIdTrainingRoute,
    AuthenticatedTeamTeamIdIndexRoute: AuthenticatedTeamTeamIdIndexRoute,
    AuthenticatedTeamTeamIdPlayerPlayerIdRoute:
      AuthenticatedTeamTeamIdPlayerPlayerIdRoute,
  }

const AuthenticatedTeamTeamIdRouteWithChildren =
  AuthenticatedTeamTeamIdRoute._addFileChildren(
    AuthenticatedTeamTeamIdRouteChildren,
  )

interface AuthenticatedTraningspassIdRouteChildren {
  AuthenticatedTraningspassIdVisaRoute: typeof AuthenticatedTraningspassIdVisaRoute
  AuthenticatedTraningspassIdIndexRoute: typeof AuthenticatedTraningspassIdIndexRoute
}

const AuthenticatedTraningspassIdRouteChildren: AuthenticatedTraningspassIdRouteChildren =
  {
    AuthenticatedTraningspassIdVisaRoute: AuthenticatedTraningspassIdVisaRoute,
    AuthenticatedTraningspassIdIndexRoute:
      AuthenticatedTraningspassIdIndexRoute,
  }

const AuthenticatedTraningspassIdRouteWithChildren =
  AuthenticatedTraningspassIdRoute._addFileChildren(
    AuthenticatedTraningspassIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedBankRoute: typeof AuthenticatedBankRoute
  AuthenticatedInstallningarRoute: typeof AuthenticatedInstallningarRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedSkapaRoute: typeof AuthenticatedSkapaRoute
  AuthenticatedTeamsRoute: typeof AuthenticatedTeamsRoute
  AuthenticatedKunskapsbankSlugRoute: typeof AuthenticatedKunskapsbankSlugRoute
  AuthenticatedTacticIdRoute: typeof AuthenticatedTacticIdRoute
  AuthenticatedTaktikbankCardIdRoute: typeof AuthenticatedTaktikbankCardIdRoute
  AuthenticatedTaktikbankReglerRoute: typeof AuthenticatedTaktikbankReglerRoute
  AuthenticatedTeamTeamIdRoute: typeof AuthenticatedTeamTeamIdRouteWithChildren
  AuthenticatedTraningspassIdRoute: typeof AuthenticatedTraningspassIdRouteWithChildren
  AuthenticatedKunskapsbankIndexRoute: typeof AuthenticatedKunskapsbankIndexRoute
  AuthenticatedOvningsbankIndexRoute: typeof AuthenticatedOvningsbankIndexRoute
  AuthenticatedTaktikbankIndexRoute: typeof AuthenticatedTaktikbankIndexRoute
  AuthenticatedTraningspassIndexRoute: typeof AuthenticatedTraningspassIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedBankRoute: AuthenticatedBankRoute,
  AuthenticatedInstallningarRoute: AuthenticatedInstallningarRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedSkapaRoute: AuthenticatedSkapaRoute,
  AuthenticatedTeamsRoute: AuthenticatedTeamsRoute,
  AuthenticatedKunskapsbankSlugRoute: AuthenticatedKunskapsbankSlugRoute,
  AuthenticatedTacticIdRoute: AuthenticatedTacticIdRoute,
  AuthenticatedTaktikbankCardIdRoute: AuthenticatedTaktikbankCardIdRoute,
  AuthenticatedTaktikbankReglerRoute: AuthenticatedTaktikbankReglerRoute,
  AuthenticatedTeamTeamIdRoute: AuthenticatedTeamTeamIdRouteWithChildren,
  AuthenticatedTraningspassIdRoute:
    AuthenticatedTraningspassIdRouteWithChildren,
  AuthenticatedKunskapsbankIndexRoute: AuthenticatedKunskapsbankIndexRoute,
  AuthenticatedOvningsbankIndexRoute: AuthenticatedOvningsbankIndexRoute,
  AuthenticatedTaktikbankIndexRoute: AuthenticatedTaktikbankIndexRoute,
  AuthenticatedTraningspassIndexRoute: AuthenticatedTraningspassIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  TShareIdRoute: TShareIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
