/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedBankRouteImport } from './routes/_authenticated/bank'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedTeamsRouteImport } from './routes/_authenticated/teams'
import { Route as TShareIdRouteImport } from './routes/t.$shareId'
import { Route as AuthenticatedTacticIdRouteImport } from './routes/_authenticated/tactic.$id'
import { Route as AuthenticatedTeamTeamIdRouteImport } from './routes/_authenticated/team.$teamId'
import { Route as AuthenticatedTeamTeamIdIndexRouteImport } from './routes/_authenticated/team.$teamId.index'
import { Route as AuthenticatedTeamTeamIdTrainingRouteImport } from './routes/_authenticated/team.$teamId.training'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedBankRoute = AuthenticatedBankRouteImport.update({
  id: '/bank',
  path: '/bank',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTeamsRoute = AuthenticatedTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const TShareIdRoute = TShareIdRouteImport.update({
  id: '/t/$shareId',
  path: '/t/$shareId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTacticIdRoute = AuthenticatedTacticIdRouteImport.update({
  id: '/tactic/$id',
  path: '/tactic/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTeamTeamIdRoute = AuthenticatedTeamTeamIdRouteImport.update({
  id: '/team/$teamId',
  path: '/team/$teamId',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTeamTeamIdIndexRoute =
  AuthenticatedTeamTeamIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedTeamTeamIdRoute,
  } as any)
const AuthenticatedTeamTeamIdTrainingRoute =
  AuthenticatedTeamTeamIdTrainingRouteImport.update({
    id: '/training',
    path: '/training',
    getParentRoute: () => AuthenticatedTeamTeamIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bank': typeof AuthenticatedBankRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/teams': typeof AuthenticatedTeamsRoute
  '/t/$shareId': typeof TShareIdRoute
  '/tactic/$id': typeof AuthenticatedTacticIdRoute
  '/team/$teamId': typeof AuthenticatedTeamTeamIdRouteWithChildren
  '/team/$teamId/training': typeof AuthenticatedTeamTeamIdTrainingRoute
  '/team/$teamId/': typeof AuthenticatedTeamTeamIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bank': typeof AuthenticatedBankRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/teams': typeof AuthenticatedTeamsRoute
  '/t/$shareId': typeof TShareIdRoute
  '/tactic/$id': typeof AuthenticatedTacticIdRoute
  '/team/$teamId/training': typeof AuthenticatedTeamTeamIdTrainingRoute
  '/team/$teamId': typeof AuthenticatedTeamTeamIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/bank': typeof AuthenticatedBankRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/teams': typeof AuthenticatedTeamsRoute
  '/t/$shareId': typeof TShareIdRoute
  '/_authenticated/tactic/$id': typeof AuthenticatedTacticIdRoute
  '/_authenticated/team/$teamId': typeof AuthenticatedTeamTeamIdRouteWithChildren
  '/_authenticated/team/$teamId/training': typeof AuthenticatedTeamTeamIdTrainingRoute
  '/_authenticated/team/$teamId/': typeof AuthenticatedTeamTeamIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/bank'
    | '/onboarding'
    | '/teams'
    | '/t/$shareId'
    | '/tactic/$id'
    | '/team/$teamId'
    | '/team/$teamId/training'
    | '/team/$teamId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/bank'
    | '/onboarding'
    | '/teams'
    | '/t/$shareId'
    | '/tactic/$id'
    | '/team/$teamId/training'
    | '/team/$teamId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/bank'
    | '/_authenticated/onboarding'
    | '/_authenticated/teams'
    | '/t/$shareId'
    | '/_authenticated/tactic/$id'
    | '/_authenticated/team/$teamId'
    | '/_authenticated/team/$teamId/training'
    | '/_authenticated/team/$teamId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  TShareIdRoute: typeof TShareIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/bank': {
      id: '/_authenticated/bank'
      path: '/bank'
      fullPath: '/bank'
      preLoaderRoute: typeof AuthenticatedBankRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/teams': {
      id: '/_authenticated/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof AuthenticatedTeamsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/t/$shareId': {
      id: '/t/$shareId'
      path: '/t/$shareId'
      fullPath: '/t/$shareId'
      preLoaderRoute: typeof TShareIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tactic/$id': {
      id: '/_authenticated/tactic/$id'
      path: '/tactic/$id'
      fullPath: '/tactic/$id'
      preLoaderRoute: typeof AuthenticatedTacticIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/team/$teamId': {
      id: '/_authenticated/team/$teamId'
      path: '/team/$teamId'
      fullPath: '/team/$teamId'
      preLoaderRoute: typeof AuthenticatedTeamTeamIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/team/$teamId/': {
      id: '/_authenticated/team/$teamId/'
      path: '/'
      fullPath: '/team/$teamId/'
      preLoaderRoute: typeof AuthenticatedTeamTeamIdIndexRouteImport
      parentRoute: typeof AuthenticatedTeamTeamIdRoute
    }
    '/_authenticated/team/$teamId/training': {
      id: '/_authenticated/team/$teamId/training'
      path: '/training'
      fullPath: '/team/$teamId/training'
      preLoaderRoute: typeof AuthenticatedTeamTeamIdTrainingRouteImport
      parentRoute: typeof AuthenticatedTeamTeamIdRoute
    }
  }
}

interface AuthenticatedTeamTeamIdRouteChildren {
  AuthenticatedTeamTeamIdTrainingRoute: typeof AuthenticatedTeamTeamIdTrainingRoute
  AuthenticatedTeamTeamIdIndexRoute: typeof AuthenticatedTeamTeamIdIndexRoute
}

const AuthenticatedTeamTeamIdRouteChildren: AuthenticatedTeamTeamIdRouteChildren =
  {
    AuthenticatedTeamTeamIdTrainingRoute: AuthenticatedTeamTeamIdTrainingRoute,
    AuthenticatedTeamTeamIdIndexRoute: AuthenticatedTeamTeamIdIndexRoute,
  }

const AuthenticatedTeamTeamIdRouteWithChildren =
  AuthenticatedTeamTeamIdRoute._addFileChildren(
    AuthenticatedTeamTeamIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBankRoute: typeof AuthenticatedBankRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedTeamsRoute: typeof AuthenticatedTeamsRoute
  AuthenticatedTacticIdRoute: typeof AuthenticatedTacticIdRoute
  AuthenticatedTeamTeamIdRoute: typeof AuthenticatedTeamTeamIdRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBankRoute: AuthenticatedBankRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedTeamsRoute: AuthenticatedTeamsRoute,
  AuthenticatedTacticIdRoute: AuthenticatedTacticIdRoute,
  AuthenticatedTeamTeamIdRoute: AuthenticatedTeamTeamIdRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  TShareIdRoute: TShareIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
